document.writeln("<div class=\'header clearfix\'>");
document.writeln("	<nav role=\'navigation\'>");
document.writeln("		<div class=\'navbar-header\'>");

document.writeln("			<div class=\'header_top hidden-xs hidden-sm hidden-md\'>");
document.writeln("				<div class=\'header_top_main\'>");
document.writeln("					<span class=\'top_links\'><a class=\'top_link\'>企业邮箱</a> | <a class=\'top_link\'>OA系统</a></span>");
document.writeln("					<span class=\'search_show_con\'>");
document.writeln("					<input type=\'search\'/>");
document.writeln("					<a href=\'search.html\'><i class=\'fa fa-search active\'></i></a>");
document.writeln("					</span>");
document.writeln("					<a class=\'top_link active\'>中文</a>");
document.writeln("					<a class=\'top_link\'>EN</a>");
document.writeln("				</div>");
document.writeln("			</div>");

document.writeln("			<div class=\'logo\'>");
document.writeln("				<a href=\'index.html\'><img src=\'img/logo.png\' alt=\'中银律师事务所\' class=\'logoimg\'></a>");
document.writeln("			</div>");
document.writeln("			<div class=\'menu\'>");
document.writeln("				<ul class=\'navbar-nav row\'>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'index.html\'><span class=\'nav_en\'>Home<br/></span>首页</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'about.html\'><span class=\'nav_en\'>About us<br/></span>关于中银</a>");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'about.html?id=1\'>中银简介</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'about.html?id=2\'>中银荣誉</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'about.html?id=3\'>中银客户</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'practices.html\'><span class=\'nav_en\'>Practice areas<br/></span>业务领域</a>");
document.writeln("					<ul class=\'submenu1 clearfix\'>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=1\'>金融证券保险法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=2\'>法律风险管理法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=3\'>公司业务法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=4\'>房地产与建筑工程法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=5\'>知识产权法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=6\'>国际业务法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=7\'>贸易救济与WTO法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=8\'>争议解决法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=9\'>刑事法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=10\'>不良资产法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href=\'practices.html?id=11\'>大宗商品交易及商品金融法律服务中心</a>");
document.writeln("					</li>");
document.writeln("					</ul>");

document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'team.html\'><span class=\'nav_en\'>Our team<br/></span>专业团队</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'agency.html\'><span class=\'nav_en\'>Global institutions<br/></span>全球机构</a>");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'agency.html?id=1\'>境内机构</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'agency.html?id=2\'>联营所</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'agency.html?id=3\'>战略合作伙伴</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'news.html\'><span class=\'nav_en\'>News center<br/></span>新闻中心</a>");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'news.html?id=1\'>中银动态</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'news.html?id=2\'>中银业绩</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'news.html?id=3\'>中银公益</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'library.html\'><span class=\'nav_en\'>Library<br/></span>中银文库</a>");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li>");
document.writeln("								<a href=\'library.html?id=1\'>中银阅读</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'library.html?id=2\'>中银文集</a>");
document.writeln("							</li>");
document.writeln("							<li>");
document.writeln("								<a href=\'library.html?id=3\'>中银法致</a>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'Join.html\'><span class=\'nav_en\'>Job opportunitie<br/></span>工作机会</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li\'>");
document.writeln("						<a href=\'contact.html\'><span class=\'nav_en\'>Contact us<br/></span>联系我们</a>");
document.writeln("					</li>");
document.writeln("					<li class=\'menu_li hidden-lg\'>");
document.writeln("						<a href=\'\'>English</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\'navtoggle hidden-lg\'>");
document.writeln("				<span class=\'mob_search\'></span>");
document.writeln("				<span class=\'mob_menu\'></span>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<div class=\'sub_search\'>");
document.writeln("			<div class=\'header-search\'>");
document.writeln("				<input type=\'text\' title=\'搜索\' class=\'form-control input-search\' placeholder=\'搜索...\' />");
document.writeln("				<div class=\'search_btn\'><span class=\'icon_search\'></span></div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</nav>");
document.writeln("</div>");